version: '3'

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - inception
    env_file: .env
    #healthcheck:
    #  test: ["CMD", "mysqladmin", "ping", "-h", "localhost"] 
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      - mariadb
    expose:
      - "9000"
    networks:
      - inception
    env_file: .env
    #healthcheck:
    #  test: ["CMD-SHELL", "curl -f https://yatang.42.fr || exit 1"] 
    restart: on-failure

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile	
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    env_file: .env
    #links: [wordpress]
    restart: on-failure

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/yatang/data/mariadb'
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/yatang/data/wordpress'

networks:
  inception:
